[build]
  command = "rm -rf node_modules && npm install --legacy-peer-deps --no-audit && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--legacy-peer-deps --no-audit"
