[build]
  command = "npm run install:ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --prefer-offline"
  CI = "false"
